import audi from "./logos/audi.png";
import bmw from "./logos/bmw.png";
import porsche from "./logos/porsche.png";
import lamborghini from "./logos/lamborghini.png";
import amg from "./logos/amg.png";
import ferrari from "./logos/ferrari.png";
import honda from "./logos/honda.png";
import mclaren from "./logos/mclaren.png";
import nissan from "./logos/nissan.png";
import aston from "./logos/aston.png";
import bentley from "./logos/bentley.png";
import lexus from "./logos/lexus.png";
import reiter from "./logos/reiter.png";
import alpine from "./logos/alpine.png";
import jaguar from "./logos/jaguar.png";
import ginetta from "./logos/ginetta.png";
import maserati from "./logos/maserati.png";
import chevrolet from "./logos/chevrolet.png";
import ktm from "./logos/ktm.png";
import lfm from "./logos/lfm.png";
import aor from "./logos/aor.png";
import es from "./logos/es.png";
import gb from "./logos/gb.png";
import hu from "./logos/hu.png";
import it from "./logos/it.png";
import de from "./logos/de.png";
import fr from "./logos/fr.png";
import be from "./logos/be.png";
import nl from "./logos/nl.png";
import au from "./logos/au.png";
import jp from "./logos/jp.png";
import us from "./logos/us.png";
import za from "./logos/za.png";

export const TRACKS = [
  {
    lfmId: 124,
    aorId: "barcelona",
    name: "Circuit de Catalunya",
    flag: es,
  },
  {
    lfmId: 125,
    aorId: "brands_hatch",
    name: "Brands Hatch Circuit",
    flag: gb,
  },
  {
    lfmId: 126,
    aorId: "hungaroring",
    name: "Hungaroring",
    flag: hu,
  },
  {
    lfmId: 127,
    aorId: "misano",
    name: "Misano",
    flag: it,
  },
  {
    lfmId: 128,
    aorId: "monza",
    name: "Autodromo Nazionale di Monza",
    flag: it,
  },
  {
    lfmId: 129,
    aorId: "nurburgring",
    name: "Nürburgring",
    flag: de,
  },
  {
    lfmId: 130,
    aorId: "paul_ricard",
    name: "Circuit de Paul Ricard",
    flag: fr,
  },
  {
    lfmId: 131,
    aorId: "silverstone",
    name: "Silverstone",
    flag: gb,
  },
  {
    lfmId: 132,
    aorId: "spa",
    name: "Circuit de Spa-Francorchamps",
    flag: be,
  },
  {
    lfmId: 133,
    aorId: "zolder",
    name: "Zolder",
    flag: be,
  },
  {
    lfmId: 134,
    aorId: "imola",
    name: "Autodromo Enzo e Dino Ferrari",
    flag: it,
  },
  {
    lfmId: 135,
    aorId: "zandvoort",
    name: "Zandvoort",
    flag: nl,
  },
  {
    lfmId: 136,
    aorId: "mount_panorama",
    name: "Mount Panorama Circuit",
    flag: au,
  },
  {
    lfmId: 137,
    aorId: "suzuka",
    name: "Suzuka Circuit",
    flag: jp,
  },
  {
    lfmId: 138,
    aorId: "laguna_seca",
    name: "Laguna Seca",
    flag: us,
  },
  {
    lfmId: 139,
    aorId: "kyalami",
    name: "Kyalami",
    flag: za,
  },
  {
    lfmId: 140,
    aorId: "oulton_park",
    name: "Oulton Park",
    flag: gb,
  },
  {
    lfmId: 141,
    aorId: "donington",
    name: "Donington Park",
    flag: gb,
  },
  {
    lfmId: 142,
    aorId: "snetterton",
    name: "Snetterton",
    flag: gb,
  },
  {
    lfmId: 143,
    aorId: "indianapolis",
    name: "Indianapolis",
    flag: us,
  },
  {
    lfmId: 144,
    aorId: "watkins_glen",
    name: "Watkins Glen",
    flag: us,
  },
  {
    lfmId: 145,
    aorId: "cota",
    name: "Circuit of the Americas",
    flag: us,
  },
  {
    lfmId: 155,
    aorId: "valencia",
    name: "Circuit Ricardo Tormo",
    flag: es,
  },
] as const;

export const CARS = {
  "alpine a110 GT4 (2018)": {
    lfmRelevant: false,
    img: alpine,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "amr v12 vantage GT3 (2013)": {
    lfmRelevant: false,
    img: aston,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "amr v8 vantage GT3 (2019)": {
    lfmRelevant: true,
    img: aston,
    usablePatch: {
      spa: "1.9.5",
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",

      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "aston martin vantage GT4 (2018)": {
    lfmRelevant: false,
    img: aston,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "audi r8 lms GT4 (2018)": {
    lfmRelevant: false,
    img: audi,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "audi r8 lms GT3 (2015)": {
    lfmRelevant: false,
    img: audi,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "audi r8 lms evo GT3 (2019)": {
    lfmRelevant: false,
    img: audi,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "audi r8 lms evo ii GT3 (2022)": {
    lfmRelevant: true,
    img: audi,
    usablePatch: {
      monza: "1.9.2",
      spa: "1.9.5",
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",

      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",

      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "bentley continental GT3 (2015)": {
    lfmRelevant: false,
    img: bentley,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "bentley continental GT3 (2018)": {
    lfmRelevant: true,
    img: bentley,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "bmw m2 cs TCX (2022)": {
    lfmRelevant: false,
    img: bmw,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "bmw m4 GT3 (2022)": {
    lfmRelevant: true,
    img: bmw,
    usablePatch: {
      barcelona: "1.9.5",
      brands_hatch: "1.9.5",
      hungaroring: "1.9.5",
      misano: "1.9.5",
      monza: "1.9.5",
      nurburgring: "1.9.5",
      paul_ricard: "1.9.5",
      silverstone: "1.9.5",
      spa: "1.9.5",
      zolder: "1.9.5",
      imola: "1.9.5",
      zandvoort: "1.9.5",
      mount_panorama: "1.9.5",
      suzuka: "1.9.5",
      laguna_seca: "1.9.5",
      kyalami: "1.9.5",
      oulton_park: "1.9.5",
      donington: "1.9.5",
      snetterton: "1.9.5",
      indianapolis: "1.9.5",
      watkins_glen: "1.9.5",
      cota: "1.9.4",
      valencia: "1.9.5",
    },
  },
  "bmw m4 GT4 (2018)": {
    lfmRelevant: false,
    img: bmw,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "bmw m6 GT3 (2017)": {
    lfmRelevant: false,
    img: bmw,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "chevrolet camaro GT4 (2017)": {
    lfmRelevant: false,
    img: chevrolet,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "emil frey jaguar g3 GT3 (2012)": {
    lfmRelevant: false,
    img: jaguar,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "ferrari 296 GT3 (2023)": {
    lfmRelevant: true,
    img: ferrari,
    usablePatch: {
      barcelona: "1.9.3",
      brands_hatch: "1.9.3",
      hungaroring: "1.9.3",
      misano: "1.9.3",
      monza: "1.9.3",
      nurburgring: "1.9.5",
      paul_ricard: "1.9.3",
      silverstone: "1.9.3",
      spa: "1.9.5",
      zolder: "1.9.3",
      imola: "1.9.3",
      zandvoort: "1.9.3",
      mount_panorama: "1.9.3",
      suzuka: "1.9.3",
      laguna_seca: "1.9.3",
      kyalami: "1.9.3",
      oulton_park: "1.9.3",
      donington: "1.9.3",
      snetterton: "1.9.3",
      indianapolis: "1.9.3",
      watkins_glen: "1.9.3",
      cota: "1.9.4",
      valencia: "1.9.3",
    },
  },
  "ferrari 488 challenge evo FERRARI CHALLENGE (2020)": {
    lfmRelevant: false,
    img: ferrari,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "ferrari 488 GT3 (2015)": {
    lfmRelevant: false,
    img: ferrari,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "ferrari 488 GT3 (2018)": {
    lfmRelevant: false,
    img: ferrari,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "ferrari 488 evo GT3 (2020)": {
    lfmRelevant: false,
    img: ferrari,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "ginetta g55 GT4 (2012)": {
    lfmRelevant: false,
    img: ginetta,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "honda nsx GT3 (2017)": {
    lfmRelevant: false,
    img: honda,
    usablePatch: {
      cota: "1.9.0",
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "honda nsx evo GT3 (2019)": {
    lfmRelevant: true,
    img: honda,
    usablePatch: {
      cota: "1.9.4",
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",

      valencia: "1.9.0",
    },
  },
  "ktm x-bow GT4 (2016)": {
    lfmRelevant: false,
    img: ktm,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "lamborghini huracán GT3 (2015)": {
    lfmRelevant: false,
    img: lamborghini,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "lamborghini huracán evo GT3 (2019)": {
    lfmRelevant: false,
    img: lamborghini,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "lamborghini huracán evo 2 GT3 (2023)": {
    lfmRelevant: true,
    img: lamborghini,
    usablePatch: {
      barcelona: "1.9.2",
      brands_hatch: "1.9.2",
      hungaroring: "1.9.2",
      misano: "1.9.2",
      monza: "1.9.2",
      nurburgring: "1.9.2",
      paul_ricard: "1.9.2",
      silverstone: "1.9.2",
      spa: "1.9.5",
      zolder: "1.9.2",
      imola: "1.9.2",
      zandvoort: "1.9.2",
      mount_panorama: "1.9.2",
      suzuka: "1.9.2",
      laguna_seca: "1.9.2",
      kyalami: "1.9.2",
      oulton_park: "1.9.2",
      donington: "1.9.2",
      snetterton: "1.9.2",
      indianapolis: "1.9.2",
      watkins_glen: "1.9.2",
      cota: "1.9.4",
      valencia: "1.9.5",
    },
  },
  "lamborghini huracán super trofeo evo2 ST (2022)": {
    lfmRelevant: false,
    img: lamborghini,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "lexus rc f GT3 (2016)": {
    lfmRelevant: false,
    img: lexus,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "maserati mc GT4 (2016)": {
    lfmRelevant: false,
    img: maserati,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "mclaren 570s GT4 (2016)": {
    lfmRelevant: false,
    img: mclaren,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "mclaren 650s GT3 (2015)": {
    lfmRelevant: false,
    img: mclaren,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "mclaren 720s GT3 (2019)": {
    lfmRelevant: false,
    img: mclaren,
    usablePatch: {
      paul_ricard: "1.9.3",
      cota: "1.9.4",
      donington: "1.9.4",
      mount_panorama: "1.9.3",
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "mclaren 720s evo GT3 (2023)": {
    lfmRelevant: true,
    img: mclaren,
    usablePatch: {
      barcelona: "1.9.5",
      brands_hatch: "1.9.5",
      hungaroring: "1.9.5",
      misano: "1.9.5",
      monza: "1.9.5",
      nurburgring: "1.9.5",
      paul_ricard: "1.9.5",
      silverstone: "1.9.5",
      spa: "1.9.5",
      zolder: "1.9.5",
      imola: "1.9.5",
      zandvoort: "1.9.5",
      mount_panorama: "1.9.5",
      suzuka: "1.9.5",
      laguna_seca: "1.9.5",
      kyalami: "1.9.5",
      oulton_park: "1.9.5",
      donington: "1.9.5",
      snetterton: "1.9.5",
      indianapolis: "1.9.5",
      watkins_glen: "1.9.5",
      cota: "1.9.5",
      valencia: "1.9.5",
    },
  },
  "mercedes amg GT3 (2015)": {
    lfmRelevant: false,
    img: amg,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "mercedes amg GT4 (2016)": {
    lfmRelevant: false,
    img: amg,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "mercedes amg GT3 (2020)": {
    lfmRelevant: true,
    img: amg,
    usablePatch: {
      barcelona: "1.9.2",
      brands_hatch: "1.9.2",
      hungaroring: "1.9.2",
      misano: "1.9.2",
      monza: "1.9.2",
      nurburgring: "1.9.5",
      paul_ricard: "1.9.2",
      silverstone: "1.9.2",
      spa: "1.9.5",
      zolder: "1.9.2",
      imola: "1.9.2",
      zandvoort: "1.9.2",
      mount_panorama: "1.9.2",
      suzuka: "1.9.2",
      laguna_seca: "1.9.2",
      kyalami: "1.9.2",
      oulton_park: "1.9.2",
      donington: "1.9.4",
      snetterton: "1.9.2",
      indianapolis: "1.9.2",
      watkins_glen: "1.9.2",
      cota: "1.9.4",
      valencia: "1.9.5",
    },
  },
  "nissan gt-r nismo GT3 (2015)": {
    lfmRelevant: false,
    img: nissan,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "nissan gt-r nismo GT3 (2018)": {
    lfmRelevant: false,
    img: nissan,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "porsche 718 cayman GT4 (2019)": {
    lfmRelevant: false,
    img: porsche,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "porsche 991 ii r GT3 (2019)": {
    lfmRelevant: false,
    img: porsche,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "porsche 991 r GT3 (2018)": {
    lfmRelevant: false,
    img: porsche,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "porsche 992 cup CUP (2022)": {
    lfmRelevant: false,
    img: porsche,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "porsche 991 ii cup CUP (2017)": {
    lfmRelevant: false,
    img: porsche,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
  "porsche 992 r GT3 (2023)": {
    lfmRelevant: true,
    img: porsche,
    usablePatch: {
      barcelona: "1.9.2",
      brands_hatch: "1.9.2",
      hungaroring: "1.9.2",
      misano: "1.9.2",
      monza: "1.9.2",
      nurburgring: "1.9.2",
      paul_ricard: "1.9.2",
      silverstone: "1.9.2",
      spa: "1.9.2",
      zolder: "1.9.2",
      imola: "1.9.2",
      zandvoort: "1.9.2",
      mount_panorama: "1.9.2",
      suzuka: "1.9.2",
      laguna_seca: "1.9.2",
      kyalami: "1.9.2",
      oulton_park: "1.9.2",
      donington: "1.9.4",
      snetterton: "1.9.2",
      indianapolis: "1.9.2",
      watkins_glen: "1.9.2",
      cota: "1.9.4",
      valencia: "1.9.5",
    },
  },
  "reiter engineering r-ex GT3 (2017)": {
    lfmRelevant: false,
    img: reiter,
    usablePatch: {
      barcelona: "1.9.0",
      brands_hatch: "1.9.0",
      hungaroring: "1.9.0",
      misano: "1.9.0",
      monza: "1.9.0",
      nurburgring: "1.9.0",
      paul_ricard: "1.9.0",
      silverstone: "1.9.0",
      spa: "1.9.0",
      zolder: "1.9.0",
      imola: "1.9.0",
      zandvoort: "1.9.0",
      mount_panorama: "1.9.0",
      suzuka: "1.9.0",
      laguna_seca: "1.9.0",
      kyalami: "1.9.0",
      oulton_park: "1.9.0",
      donington: "1.9.0",
      snetterton: "1.9.0",
      indianapolis: "1.9.0",
      watkins_glen: "1.9.0",
      cota: "1.9.0",
      valencia: "1.9.0",
    },
  },
} as const;

export const PROVIDERS = {
  LFM: {
    logo: lfm,
  },
  AOR: {
    logo: aor,
  },
} as const;
